services:
  postgres:
    image: postgres:17-alpine
    container_name: syk-inn-api-dev-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: syk-inn-api
    ports:
      - '7969:5432'
