apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: syk-inn-api
  namespace: tsm
  labels:
    team: tsm
spec:
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        name: syk-inn-api-instance
        cascadingDelete: false
        databases:
          - name: syk-inn-api
            envVarPrefix: DB
        diskAutoresize: true
        highAvailability: false
        diskType: SSD
        insights:
          enabled: true
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
        pointInTimeRecovery: true
        tier: db-f1-micro
  image: {{ image }}
  replicas:
    min: 2
    max: 6
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health
  readiness:
    path: /internal/health
  startup:
    path: /internal/health
    initialDelay: 60
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 30m
      memory: 256Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
  kafka:
    pool: nav-prod
  accessPolicy:
    inbound:
      rules:
        - application: syk-inn
    outbound:
      rules:
        - application: syfohelsenettproxy
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: syfosmregler
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: syfosmregister
          namespace: teamsykmelding
          cluster: prod-gcp
  secureLogs:
    enabled: true
  env:
    - name: SYFOHELSENETTPROXY_SCOPE
      value: api://prod-gcp.teamsykmelding.syfohelsenettproxy/.default
    - name: SYFOSMREGLER_SCOPE
      value: api://prod-gcp.teamsykmelding.syfosmregler/.default
    - name: SYFOSMREGISTER_SCOPE
      value: api://prod-gcp.teamsykmelding.syfosmregister/.default
    - name: TSM_PDL_ENDPOINT_URL
      value: http://tsm-pdl-cache
    - name: BTSYS_ENDPOINT_URL
      value: http://btsys-api.team-rocket
    - name: SYFOHELSENETTPROXY_BASE_URL
      value: http://syfohelsenettproxy.teamsykmelding
