apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: syk-inn-api
  namespace: tsm
  labels:
    team: tsm
  annotations:
    texas.nais.io/enabled: "true"
spec:
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        name: syk-inn-api-instance
        cascadingDelete: false
        databases:
          - name: syk-inn-api
            envVarPrefix: DB
        diskAutoresize: true
        highAvailability: false
        diskType: SSD
        insights:
          enabled: true
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
        pointInTimeRecovery: true
        tier: db-f1-micro
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health
  readiness:
    path: /internal/health
  startup:
    path: /internal/health
    initialDelay: 60
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 30m
      memory: 512Mi
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  kafka:
    pool: nav-dev
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  accessPolicy:
    inbound:
      rules:
        - application: syk-inn
    outbound:
      rules:
        - application: syfohelsenettproxy
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: syfosmregler
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: syfosmregister
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: smpdfgen
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: tsm-pdl-cache
          namespace: tsm
          cluster: dev-gcp
        - application: btsys-api
          namespace: team-rocket
          cluster: dev-gcp
  ingresses:
    - "https://syk-inn-api.intern.dev.nav.no"
  secureLogs:
    enabled: true
  env:
    - name: SYFOHELSENETTPROXY_SCOPE
      value: api://dev-gcp.teamsykmelding.syfohelsenettproxy/.default
    - name: SYFOSMREGLER_SCOPE
      value: api://dev-gcp.teamsykmelding.syfosmregler/.default
    - name: SYFOSMREGISTER_SCOPE
      value: api://dev-gcp.teamsykmelding.syfosmregister/.default
    - name: SMPDFGEN_SCOPE
      value: api://dev-gcp.teamsykmelding.smpdfgen/.default
    - name: TSMPDL_SCOPE
      value: api://dev-gcp.tsm.tsm-pdl-cache/.default
    - name: LEGE_SUSPENSJON_PROXY_SCOPE
      value: api://dev-gcp.team-rocket.btsys-api/.default
    - name: TSM_PDL_ENDPOINT_URL
      value: http://tsm-pdl-cache
    - name: BTSYS_ENDPOINT_URL
      value: http://btsys-api.team-rocket
    - name: SYFOHELSENETTPROXY_URL
      value: http://syfohelsenettproxy.teamsykmelding

