apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  # TODO: Temporary deploy this as its own app
  name: syk-inn-api-ktor
  namespace: tsm
  labels:
    team: tsm

spec:
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        # TODO: Temporary deploy this as its own app
        name: syk-inn-api-ktor-instance
        cascadingDelete: false
        databases:
          # TODO: Temporary deploy this as its own app
          - name: syk-inn-api-ktor
            envVarPrefix: DB
        diskAutoresize: true
        highAvailability: false
        diskType: SSD
        insights:
          enabled: true
        tier: db-f1-micro
        flags:
          - name: cloudsql.enable_pgaudit
            value: "true"
          - name: pgaudit.log
            value: "write,ddl,role"
          - name: pgaudit.log_parameter
            value: "on"
          - name: cloudsql.logical_decoding
            value: "on"
  kafka:
    pool: nav-dev

  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 30m
      memory: 512Mi

  liveness:
    path: /internal/health/alive
  readiness:
    path: /internal/health/ready
  preStopHook:
    http:
      path: /internal/shutdown
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java

  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      allowAllUsers: true

  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/docs

  accessPolicy:
    inbound:
      rules:
        - application: syk-inn
        - application: zara
    outbound:
      rules:
        - application: logging
          namespace: nais-system
        - application: syfohelsenettproxy
          namespace: teamsykmelding
        - application: tsm-pdl-cache
          namespace: tsm
        - application: btsys-api
          namespace: team-rocket
  env:
    - name: SOURCE_VERSION_URL
      value: {{ sourceVersionURL }}
