apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: syk-inn-api
  namespace: tsm
  labels:
    team: tsm
  annotations:
    texas.nais.io/enabled: "true"
spec:
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        name: syk-inn-api-instance
        cascadingDelete: false
        databases:
          - name: syk-inn-api
            envVarPrefix: DB
        diskAutoresize: true
        highAvailability: true
        diskType: SSD
        insights:
          enabled: true
        tier: db-custom-1-3840
        flags:
          - name: cloudsql.enable_pgaudit
            value: "true"
          - name: pgaudit.log
            value: "write,ddl,role"
          - name: pgaudit.log_parameter
            value: "on"
          - name: cloudsql.logical_decoding
            value: "on"
  image: {{ image }}
  replicas:
    min: 2
    max: 10
    scalingStrategy:
      cpu:
        thresholdPercentage: 50
      kafka:
        consumerGroup: syk-inn-api-consumer
        threshold: 500
        topic: tsm.sykmeldinger
  port: 8080
  liveness:
    path: /internal/health
  readiness:
    path: /internal/health
  startup:
    path: /internal/health
    initialDelay: 60
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 1024m
      memory: 1Gi
  azure:
    application:
      enabled: true
      tenant: nav.no
  kafka:
    pool: nav-prod
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
        - application: syfohelsenettproxy
          namespace: teamsykmelding
        - application: syfosmregler
          namespace: teamsykmelding
        - application: syfosmregister
          namespace: teamsykmelding
        - application: smpdfgen
          namespace: teamsykmelding
        - application: tsm-pdl-cache
          namespace: tsm
        - application: btsys-api
          namespace: team-rocket
  env:
    - name: SYFOHELSENETTPROXY_SCOPE
      value: api://prod-gcp.teamsykmelding.syfohelsenettproxy/.default
    - name: SYFOSMREGLER_SCOPE
      value: api://prod-gcp.teamsykmelding.syfosmregler/.default
    - name: SYFOSMREGISTER_SCOPE
      value: api://prod-gcp.teamsykmelding.syfosmregister/.default
    - name: SMPDFGEN_SCOPE
      value: api://prod-gcp.teamsykmelding.smpdfgen/.default
    - name: TSMPDL_SCOPE
      value: api://prod-gcp.tsm.tsm-pdl-cache/.default
    - name: LEGE_SUSPENSJON_PROXY_SCOPE
      value: api://prod-gcp.team-rocket.btsys-api/.default
    - name: TSM_PDL_ENDPOINT_URL
      value: http://tsm-pdl-cache
    - name: BTSYS_ENDPOINT_URL
      value: http://btsys-api.team-rocket
    - name: SYFOHELSENETTPROXY_URL
      value: http://syfohelsenettproxy.teamsykmelding
