ktor {
  deployment {
    port = 8080
    shutdownTimeout = 15000
  }
  application {
    modules = [no.nav.tsm.ApplicationKt.module]
  }
}

app {
  name = "local-pod"
  name = ${?POD_NAME}
  runtime = "local"
}

sykmelding {
  retention: P1D // iso standard
}

postgres {
  sslCert = "scripts/certs/cert.pem"
  sslKeyPk8 = "scripts/certs/key.pk8"
  url = "postgresql://localhost:7969/syk-inn-api?sslrootcert=scripts/certs/root-cert.pem&sslcert="${postgres.sslCert}"&sslkey="${postgres.sslKeyPk8}"&sslmode=verify-ca"
  r2 = "postgresql://localhost:7969/syk-inn-api?sslRootCert=scripts/certs/root-cert.pem&sslMode=verify-ca"
  username = "user"
  username = ${?DB_USERNAME}
  password = "password"
  password = ${?DB_PASSWORD}
  schema = "new-api"
}

kafka {
  config {
    "bootstrap.servers" = "localhost:9092"
    "bootstrap.servers" = ${?BOOTSTRAP_SERVERS}
    "security.protocol" = "PLAINTEXT"
  }

  input-producer {
    delay: 5000
  }
  sykmelding-consumer {
    long-poll: 10000
  }
}
