ktor {
  deployment {
    port = 8080
    shutdownTimeout = 15000
  }
  application {
    modules = [no.nav.tsm.ApplicationKt.module]
  }
}

app {
  name = ${NAIS_POD_NAME}
  runtime = ${NAIS_CLUSTER_NAME}
  version = ${SOURCE_VERSION_URL}
}

auth {
  entra {
    audience = ${AZURE_APP_CLIENT_ID}
    openid {
      issuer: ${AZURE_OPENID_CONFIG_ISSUER}
      jwks: ${AZURE_OPENID_CONFIG_JWKS_URI}
    }
  }
}

postgres {
  jdbc = ${DB_JDBC_URL}
  r2dbc = {
    url = "r2dbc:postgresql://"${DB_HOST}":"${DB_PORT}"/"${DB_DATABASE}"?sslRootCert="${DB_SSLROOTCERT}"&sslMode=verify-ca"
    sslCert = ${DB_SSLCERT}
    sslKeyPk8 = ${DB_SSLKEY_PK8}
  }
  username = ${DB_USERNAME}
  password = ${DB_PASSWORD}
  schema = "new-api"
}

sykmelding {
  retention: P365D
}

kafka {
  config {
    "bootstrap.servers" = ${KAFKA_BROKERS}
    "security.protocol" = "SSL"
    "ssl.truststore.location" = ${KAFKA_TRUSTSTORE_PATH}
    "ssl.truststore.password" = ${KAFKA_CREDSTORE_PASSWORD}
    "ssl.truststore.type" = "jks"
    "ssl.keystore.location" = ${KAFKA_KEYSTORE_PATH}
    "ssl.keystore.password" = ${KAFKA_CREDSTORE_PASSWORD}
    "ssl.keystore.type" = "PKCS12"
  }
  input-producer {
    delay: PT10S
    hungTimeout: PT5M
  }
  sykmelding-consumer {
    long-poll: PT10S
  }
}

texas {
  token_endpoint = ${NAIS_TOKEN_ENDPOINT}
}

external {
  tsm-pdl-cache = "http://tsm-pdl-cache"
  syfohelsenettproxy = "http://syfohelsenettproxy.teamsykmelding"
  btsys = "http://btsys-api.team-rocket"
}
