ktor {
  deployment {
    port = 8080
    shutdownTimeout = 15000
  }
  application {
    modules = [no.nav.tsm.ApplicationKt.module]
  }
}

postgres {
  jdbc = ${DB_JDBC_URL}
  username = ${DB_USERNAME}
  password = ${DB_PASSWORD}
  schema = "new-api"
}

kafka {
  sykmeldingConsumer {
    longPoll: PT10S
  }
}

auth {
  entra {
    audience = ${AZURE_APP_CLIENT_ID}
    openid {
      issuer: ${AZURE_OPENID_CONFIG_ISSUER}
      jwks: ${AZURE_OPENID_CONFIG_JWKS_URI}
    }
  }
}

app {
  name = ${NAIS_POD_NAME}
  runtime = ${NAIS_CLUSTER_NAME}
  version = ${SOURCE_VERSION_URL}

  sykmelding {
    retention: P365D
  }

  jobs {
    inputProducer {
      delay: PT10S
      hungTimeout: PT5M
    }
    juridiskProducer {
      delay: PT30S
      hungTimeout: PT60M
    }
    sykmeldingDeleter {
      interval: PT3H
    }
  }
}

external {
  texas {
    tokenEndpoint = ${NAIS_TOKEN_ENDPOINT}
  }
  tsmPdlCache = "http://tsm-pdl-cache"
  syfoHelsenettproxy = "http://syfohelsenettproxy.teamsykmelding"
  btsys = "http://btsys-api.team-rocket"
}
