ktor {
  deployment {
    port = 8080
  }
  application {
    modules = [no.nav.tsm.ApplicationKt.module]
  }
}

postgres {
  url = "jdbc:postgresql://localhost:7969/syk-inn-api"
  url = ${?DB_JDBC_URL}
  username = "postgres"
  username = ${?DB_USERNAME}
  password = "password"
  password = ${?DB_PASSWORD}
}

kafka {
  config {
    "bootstrap.servers" = "localhost:9092"
    "bootstrap.servers" = ${?BOOTSTRAP_SERVERS}
    "security.protocol" = "PLAINTEXT"
  }
}
