ktor {
  deployment {
    port = 8080
  }
  application {
    modules = [no.nav.tsm.ApplicationKt.module]
  }
}

postgres {
  url = "jdbc:postgresql://localhost:7969/syk-inn-api"
  username = "postgres"
  password = "password"
}

kafka {
  config {
    "bootstrap.servers" = "localhost:9092"
    "security.protocol" = "PLAINTEXT"
  }
}
