spring:
  # Disable auth in tests
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration
  flyway:
    enabled: true
  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
  kafka:
    bootstrap-servers: localhost:9092
    security:
      protocol: plaintext

services:
  teamsykmelding:
    syfohelsenettproxy:
      url: http://localhost:8081/syfohelsenettproxy
    pdlcache:
      url: "http://localhost:8083/pdlcache"
  external:
    btsys:
      url: "http://localhost:8082/btsys"

nais:
  token_endpoint: "http://localhost:8084/nais/token"
  cluster: "test"

kafka:
  topics:
    sykmeldinger-input: "foo-bar"
    sykmeldinger: "baz-qux"
